language: C
dist: xenial

jobs:
  include:
    - name: Style check
      addons:
       apt:
         update: true
         packages: cmake
      install:
       - wget https://github.com/uncrustify/uncrustify/archive/uncrustify-0.66.1.tar.gz
       - tar xzf uncrustify-0.66.1.tar.gz
       - cd uncrustify-uncrustify-0.66.1
       - mkdir build
       - cd build
       - cmake -DCMAKE_BUILD_TYPE=Release ..
       - make -j
       - export PATH=$PWD:$PATH
       - cd ../../
       - uncrustify --version
      script: ./scripts/pretty.sh check
