language: C
dist: xenial

jobs:
  include:
    - name: Build
      addons:
        apt:
          update: true
          packages: cmake
      script: ./scripts/pretty.sh check
    - name: Style
      script:
       - wget https://github.com/uncrustify/uncrustify/archive/uncrustify-0.66.1.tar.gz
       - tar xzf uncrustify-0.66.1.tar.gz
       - cd uncrustify-uncrustify-0.66.1
       - mkdir build
       - cd build
       - cmake -DCMAKE_BUILD_TYPE=Release ..
       - make -j
       - export PATH=$PWD:$PATH
       - cd ../../
       - uncrustify --version
