language: C
dist: xenial

addons:
  apt:
    update: true
    packages: cmake

jobs:
  include:
    - name: Build & test
      script:
       - mkdir build
       - cd build
       - cmake .. -DCMAKE_BUILD_TYPE=Release
       - make -j
       - make -j test
    - name: Build & style check
      install:
       - wget https://github.com/uncrustify/uncrustify/archive/uncrustify-0.66.1.tar.gz
       - tar xzf uncrustify-0.66.1.tar.gz
       - cd uncrustify-uncrustify-0.66.1
       - mkdir build
       - cd build
       - cmake -DCMAKE_BUILD_TYPE=Release ..
       - make -j
       - export PATH=$PWD:$PATH
       - cd ../../
       - uncrustify --version
      script: ./scripts/pretty.sh check
